### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by jigadijac** [thejosejorge/futcal-for-scriptable#13]
Hi, I followed the instruction give for custom background image. I created a background for the widget, named the file background.png and added it to the folder. But the script is still showing a black background. Is there anything am doing wrong?

**Comment by thejosejorge** [comment]
Hi @jigadijac,

I have just tried it and it's working for me!

Can you please confirm the following?
- Image is inside the Futcal folder
- Image is named "background.png" and not "background.PNG" for example? (Capitalization is important on this version, plan is to improve this behaviour)

I am also working on an update that will simplify this process a lot.

**Comment by jigadijac** [comment]
Hi, thank I managed to fix it. It was the file extension that was giving the problem :)

**Comment by thejosejorge** [comment]
Great, glad it's working now!
I had some problems with the extension in the past as well, that's why I am working on a simpler way to configure it! :)

Since it's working I will close the issue, let me know if you find any other problems!
