### ISSUE TITLE
Opponent wrong with showOnlyOpposition: true

### ISSUE THREAD

**Issue by thisisevanfox** [thejosejorge/futcal-for-scriptable#14]
Hi, 

I found a bug: with "showOnlyOpposition:true" and Bayern Munich (Id: 9823) the display of the "current" opponent is wrong. The widget shows Bayern Munich, but Bayern played against Hoffenheim yesterday. The result is correct.

Screenshot: https://imgur.com/NGThfOG

**Comment by thejosejorge** [comment]
Hi @thisisevanfox,

You are right, thank you so much for reporting!
There was a problem with the code I committed yesterday. I used GitHub Desktop for the first time and apparently it committed an intermediate version that I only used for testing.
Please check the latest version that contains the correct code!

**Comment by thisisevanfox** [comment]
Nice, everything is fine now 👍 Thank you.

**Comment by thejosejorge** [comment]
Thanks for the confirmation! I will close the issue now.
