### ISSUE TITLE
Adding Korean Language

### ISSUE THREAD

**Issue by dp0973** [thejosejorge/futcal-for-scriptable#20]
I can give you some help with translation in Korean.

**Comment by thejosejorge** [comment]
Hi @dp0973,

That would be awesome!
We would need the translation for the following strings:

            championsLeague: "Champions League",
            championsLeagueQualification: "Champions League Q.",
            europaLeague: "Europa League",
            europaLeagueQualification: "Europa League Q.",
            uefaSuperCup: "UEFA Super Cup",
            cup: "Cup",
            leagueCup: "League Cup",
            superCup: "Super Cup",
            clubFriendlies: "Friendly",
            quarterFinal: "QF",
            semiFinal: "SF",
            final: "F",
            matchTitleNext: "Next",
            matchRound: "R",
            home: "H",
            away: "A",
            matchDateToday: "Today",
            matchDateTomorrow: "Tomorrow",
            postponed: "Postponed",
            cancelled: "Cancelled",
            halfTime: "HT",
            tableHeaderTeam: "T",
            tableHeaderPlayed: "M",
            tableHeaderWins: "W",
            tableHeaderDraws: "D",
            tableHeaderLosses: "L",
            tableHeaderPoints: "P",
            noDataAvailable: "No data",
            nointernetConnection: "Internet connection required"

If you can keep them short (approximately the same length as the English version if possible) that would be great as we don't have a lot of space in the UI. As you can see I had to abbreviate a lot already! :)

Please let me know if any of them is not clear!

Thanks,
Jose

**Comment by dp0973** [comment]
championsLeague: "챔피언스 리그",
        championsLeagueQualification: "챔피언스 리그 예선.",
        europaLeague: "유로파 리그",
        europaLeagueQualification: "유로파 리그 예선.",
        uefaSuperCup: "UEFA 슈퍼 컵",
        cup: "컵",
        leagueCup: "리그 컵",
        superCup: "슈퍼 컵",
        clubFriendlies: "친선",
        quarterFinal: "8강",
        semiFinal: "4강",
        final: "결승",
        matchTitleNext: "다음",
        matchRound: "R",
        home: "홈",
        away: "원",
        matchDateToday: "오늘",
        matchDateTomorrow: "내일",
        postponed: "연기됨",
        cancelled: "취소됨",
        halfTime: "하프",
        tableHeaderTeam: "팀",
        tableHeaderPlayed: "M",
        tableHeaderWins: "승",
        tableHeaderDraws: "무",
        tableHeaderLosses: "패",
        tableHeaderPoints: "점",
        noDataAvailable: "정보 없음",
        nointernetConnection: "인터넷 연결 필요"

**Comment by dp0973** [comment]
I couldn't translate R and M in one letter, but i think users can understand though.

**Comment by thejosejorge** [comment]
Hi @dp0973,

Great, thank you so much, I will try it later today and perform some tests.
Regarding R (round) and M (matches played), if you need 2 letters I don't see a problem with that! When required I am already using 2 letters!

Thanks,
Jose

**Comment by dp0973** [comment]
If possible, 'M' should be '경기'.
R is okay because it is often used when we indicate round in Korea, and also round cannot be reduced under 2 letters. (at least 3 '라운드')

**Comment by thejosejorge** [comment]
Great, thanks! Final file:

            championsLeague: "챔피언스 리그",
            championsLeagueQualification: "챔피언스 리그 예선",
            europaLeague: "유로파 리그",
            europaLeagueQualification: "유로파 리그 예선",
            uefaSuperCup: "UEFA 슈퍼 컵",
            cup: "컵",
            leagueCup: "리그 컵",
            superCup: "슈퍼 컵",
            clubFriendlies: "친선",
            quarterFinal: "8강",
            semiFinal: "4강",
            final: "결승",
            matchTitleNext: "다음",
            matchRound: "R",
            home: "홈",
            away: "원",
            matchDateToday: "오늘",
            matchDateTomorrow: "내일",
            postponed: "연기됨",
            cancelled: "취소됨",
            halfTime: "하프",
            tableHeaderTeam: "팀",
            tableHeaderPlayed: "경기",
            tableHeaderWins: "승",
            tableHeaderDraws: "무",
            tableHeaderLosses: "패",
            tableHeaderPoints: "점",
            noDataAvailable: "정보 없음",
            nointernetConnection: "인터넷 연결 필요"

I have tested it and it looks great!
For small widgets I noticed "경기" can be too long so it may be replaced with "...". I think that's OK, people will understand and I actually noticed the same happens in the FotMob app as well :)

**Comment by thejosejorge** [comment]
Change added, thanks for the support!
Please let me know if you find any issues!

**Comment by thejosejorge** [comment]
Closed.
