### ISSUE TITLE
Previous / Next matches wrong information

### ISSUE THREAD

**Issue by thejosejorge** [thejosejorge/futcal-for-scriptable#25]
FotMob seems to be changing their API structure / data so the widget needs to be adapted to these changes.
One of the impacted areas is the Next / Previous matches.

**Comment by michel0271** [comment]
same here... Previous Works, next show "no Data"

**Comment by thejosejorge** [comment]
Hi @michel0271,

This should be fixed in the latest version, can you please confirm?

The only reason I am keeping the ticket open is because I see they haven't fully migrated the API and I want to make sure the changes are OK everywhere.

Thanks,
Jose

**Comment by michel0271** [comment]
> Hi @michel0271,
> 
> This should be fixed in the latest version, can you please confirm?
> 
> The only reason I am keeping the ticket open is because I see they haven't fully migrated the API and I want to make sure the changes are OK everywhere.
> 
> Thanks,
> Jose

@thejosejorge Hi, thanks for your reply. Yes it works perfectly again! You can close the bug ticket. Greetings michel

**Comment by thejosejorge** [comment]
Closed.
