### ISSUE TITLE
Widget no longer shows data

### ISSUE THREAD

**Issue by michel0271** [thejosejorge/futcal-for-scriptable#26]
As of today, my widget no longer works.

greet Michel
![IMG_0289](https://user-images.githubusercontent.com/39130531/121566886-3f9cc380-ca1e-11eb-8ecd-aa6ce1505fd1.jpeg)
![IMG_0290](https://user-images.githubusercontent.com/39130531/121566894-41668700-ca1e-11eb-86c8-b960d7f07798.jpeg)

**Comment by thejosejorge** [comment]
Hi Michel,

FotMob changed their API.
I just deployed a quick fix, please check.

Thanks,
Jose

**Comment by michel0271** [comment]
Many Thanks! It works again ☺️
