### ISSUE TITLE
Error caused by tournament data API change

### ISSUE THREAD

**Issue by j43h4k** [thejosejorge/futcal-for-scriptable#29]
![image](https://user-images.githubusercontent.com/85357794/125286066-518fc000-e356-11eb-9f70-020f54481938.png)

**Comment by thejosejorge** [comment]
Hi @j43h4k,

This was another API change, please try the latest version.

Thanks,
Jose

**Comment by j43h4k** [comment]
> Hi @j43h4k,
> 
> 
> 
> This was another API change, please try the latest version.
> 
> 
> 
> Thanks,
> 
> Jose

Thank you very much.  It works!!

**Comment by thejosejorge** [comment]
Perfect, closing the ticket!
