### ISSUE TITLE
Are other sports possible?

### ISSUE THREAD

**Issue by DanielZ3108** [thejosejorge/futcal-for-scriptable#31]
Can you program such a widget for the German ice hockey league?

Unfortunately, there is currently nothing of this kind for the German ice hockey league. Do you have a way to create such a thing?

**Comment by thejosejorge** [comment]
Hi @DanielZ3108,

The script could be adapted for other sports if an API with all the information is available.
In terms of UI everything could remain the same, the only changes required would be related to adaptations to the API itself.

This is not part of the scope of this script (therefore closing as "wontfix") but if you are able to provide me a good API I could look into creating a separate script when I have time.

Thanks,
José
