### ISSUE TITLE
Previous match is showing wrong information

### ISSUE THREAD

**Issue by j43h4k** [thejosejorge/futcal-for-scriptable#32]
![image](https://user-images.githubusercontent.com/85357794/131262539-db8f3e7f-6943-48f2-9bc1-b682f3c2cc70.jpeg)

**Comment by hangoon-p** [comment]
**Change the code on Line166:**
`const previousMatch = teamData.fixtures[0];
`

**to:**
```
for (let i = 0; i < teamData.fixtures.length; i++) {
	if (teamData.fixtures[i].id === nextMatch.id) {
		var pre_match_id = i - 1;
		break;
	}
}
const previousMatch = teamData.fixtures[pre_match_id];
```

**It will work.**

**Comment by j43h4k** [comment]
YES!!! It works. Thank you very much.

**Comment by michel0271** [comment]
I am also seeing incorrect information from the previous game
![IMG_0552](https://user-images.githubusercontent.com/39130531/132981606-1e631401-1d05-4716-94db-d9a4e347b766.jpeg)

**Comment by michel0271** [comment]
Unfortunately, entering the code doesn't work for me

**Comment by michel0271** [comment]
can you help please?

**Comment by hangoon-p** [comment]
> can you help please?

As my comment above, all you need to do is replace the code on Line 166 to my code.
It is not pretty, but should work just fine if you did it right.
If you did something wrong, I think it wouldn't work with an error message.

I forked thejosejorge's code to my repository to maintain my personal tiny modification.
So you may refer it if you are not sure what you have to do. 
(Compare the whole code in the function 'addWidgetMatches' between thejosejorge's code and mine)

**Comment by michel0271** [comment]
> > can you help please?
> 
> As my comment above, all you need to do is replace the code on Line 166 to my code.
> It is not pretty, but should work just fine if you did it right.
> If you did something wrong, I think it wouldn't work with an error message.
> 
> I forked thejosejorge's code to my repository to maintain my personal tiny modification.
> So you may refer it if you are not sure what you have to do.
> (Compare the whole code in the function 'addWidgetMatches' between thejosejorge's code and mine)

on Line 166 i have this
![IMG_0579](https://user-images.githubusercontent.com/39130531/133898217-1ad938d3-bb87-47da-a0ff-07a35cb4b838.jpeg)

**Comment by hangoon-p** [comment]
> > > can you help please?
> > 
> > 
> > As my comment above, all you need to do is replace the code on Line 166 to my code.
> > It is not pretty, but should work just fine if you did it right.
> > If you did something wrong, I think it wouldn't work with an error message.
> > I forked thejosejorge's code to my repository to maintain my personal tiny modification.
> > So you may refer it if you are not sure what you have to do.
> > (Compare the whole code in the function 'addWidgetMatches' between thejosejorge's code and mine)
> 
> on Line 166 i have this
> ![IMG_0579](https://user-images.githubusercontent.com/39130531/133898217-1ad938d3-bb87-47da-a0ff-07a35cb4b838.jpeg)

In your case you should look at Line 163.
You could’ve see the code not just the number. On my first comment I wrote the both code to change and to replace for you to find and fix it.

**Comment by michel0271** [comment]
Thank you, that worked

**Comment by root-devvoo** [comment]
Thank you so much! I also solved by that solution. :)

**Comment by thejosejorge** [comment]
Hi guys,

Apologies for the delay on the response!
Thanks @hangoon-p, I saw the fix you provided so I was waiting to have other changes in order to update the script. I have incorporated this (API change on Fixtures list) and another fix (API change on League table) in the latest version of the script.

Closing the ticket.

Thanks,
José
