### ISSUE TITLE
Change TeamID with a parameter

### ISSUE THREAD

**Issue by cl4udiu5** [thejosejorge/futcal-for-scriptable#35]
I'd like to see changing TeamID with parameter if possible.
Would be helpful for many I think.
So I can have the script for more than one team on homescreen widgets.
And the other parameters like "showMatchesRound" for example divided by ; maybe in the homescreen widget settings.
![IMG_6646](https://user-images.githubusercontent.com/74124378/157428988-7e580f1f-4bbe-4039-b825-0f6b2d13bced.jpg)

**Comment by thejosejorge** [comment]
Hi @cl4udiu5,

This is how I was doing it originally but people were claiming it was not easy to configure so I decided to move all configurations to the main file. If you want to have several widgets for different teams / with different configurations you can duplicate the script within Scriptable.

Thanks,
José
