### ISSUE TITLE
Error: Cannot download the file from ICloud because the file does not exist

### ISSUE THREAD

**Issue by koni-ey** [thejosejorge/futcal-for-scriptable#36]
Hey Guys,
Widget looks absolutely stunning! But i am currently not able to get it working.
Im still on the default setting and copied the futcal.js in the scriptable folder as recommended. When excectuing i get an 
"Error: Data could not be read because of wrong format. Trying to read cached data: teamData.json" followed by a "Error: Cannot download the file from ICloud because the file does not exist."
Am i missing something? 
Thanks for the help! :)

**Comment by thejosejorge** [comment]
Hi @koni-ey,

Since yesterday I can no longer access the FotMob API. I will have a better look when I have time but I believe FotMob may have changed the way data is exposed and possibly no longer accessible.

In case anyone has more information please let me know!

Thanks,
José

**Comment by thejosejorge** [comment]
Hi @koni-ey, it seems the API is back to normal! Have you retried?

**Comment by koni-ey** [comment]
Yeeees! Everything working as described! Keep up the great work:)

**Comment by thejosejorge** [comment]
Great!

Closing the ticket!
