### ISSUE TITLE
Futcal is not working

### ISSUE THREAD

**Issue by j43h4k** [thejosejorge/futcal-for-scriptable#37]
No more information updated and stuck on last match.  The latest version of futcal is installed, and all patches have already been completed.

**Comment by beratgashi** [comment]
+1

**Comment by thejosejorge** [comment]
FotMob have been changing their API almost every week. This is creating several issues and forcing very frequent fixes.
I am aware of the issue reported, however, before changing anything else, I will wait a couple of weeks and check if the API stabilises.

Thanks,
José

**Comment by j43h4k** [comment]
OK. I really need this. Thank you for information and your work.

**Comment by beratgashi** [comment]
@thejosejorge i miss this widget man 😣

**Comment by hangoon-p** [comment]
Certainly we will have to wait @thejosejorge 's update for this problem.
In the meantime, you follow my ugly but working solution as below.

You can simply change every `${baseApiUrl}/teams`  to `${baseApiUrl}/api/teams` in the script.

It is easy to do with find and replace function of any text editor.

**Comment by beratgashi** [comment]
@hangoon-p maybe we can add only **api to the defined variable at the top! should i add ** too?

**Comment by hangoon-p** [comment]
> @hangoon-p maybe we can add only **api to the defined variable at the top! should i add ** too?

Sorry. It is mistakenly added. You should not add ** but just api/.
I edited my comment above. Please take a look again.

**Comment by beratgashi** [comment]
@hangoon-p i've just added the /api to the defined variable $baseApiUrl and it worked!

Thank you so much dude, you saved my day.

**Comment by hangoon-p** [comment]
@beratgashi I am happy for 

> @hangoon-p i've just added the /api to the defined variable $baseApiUrl and it worked!
> 
> Thank you so much dude, you saved my day.

glad it helped you.
have a nice day

**Comment by thejosejorge** [comment]
@hangoon-p I hadn't had the chance to look for the new API URL format, so thank you for doing that!

Simplest solution was to add the "/api" string only to `teamDataApiUrl`, since it seems `matchDetailsApiUrl` or the TapUrls haven't changed (yet). However the behaviour when tapping the different sections seems still a bit unstable.
I have now added this change to the code, but will keep monitoring this - has said FotMob have been changing their API almost every week.

Thanks,
José

**Comment by beratgashi** [comment]
@thejosejorge can you please tell me how can i make rounded the **highlightedRow**

**Comment by thejosejorge** [comment]
Hi @beratgashi,
The "showRowPositionHighlight" is using the table cells color to add the highlight so it can't be rounded. If you want to have a rounded effect you would need to use the same approach I use for "showCirclePositionHighlight", adding the highlight as an image - although this is not a trivial change.

Closing the ticket as the original issue is fixed.
