### ISSUE TITLE
Exception Occurred Error on line 166:50

### ISSUE THREAD

**Issue by TheBreznsoiza** [thejosejorge/futcal-for-scriptable#38]
`Exception Occurred
Error on line 166:50: TypeError:
undefined is not an object (evaluating
'nextMatch.id‘)`

Hello, got this error since today. Season is over so „nextMatch.id“ is kind of empty? 

Or futmob has changed something again?

**Comment by beratgashi** [comment]
And i'm getting this error message 

`Error: The data couldn’t be read because it isn’t in the correct format.`

**Comment by thejosejorge** [comment]
Please check the latest version.

**Comment by TheBreznsoiza** [comment]
> Please check the latest version.

Done, works again fine. Thanks for the fast bugfix @thejosejorge
